In [44]:
import pandas as pd

In [45]:
df = pd.read_csv("data.csv")
df.head(2)

,renda_mensal,score_credito,estado_civil,tempo_emprego_anos,patrimonio,dividas_pendentes,risco
0,8470,505,casado,0,73125,19317,1
1,2060,450,solteiro,12,25078,7659,1

In [46]:
categorias = df["estado_civil"].unique()
print(categorias)

<StringArray>
['casado', 'solteiro', 'divorciado']
Length: 3, dtype: str

In [47]:
mapa = {cat: i for i, cat in enumerate(categorias)}
print(mapa)

{'casado': 0, 'solteiro': 1, 'divorciado': 2}

In [37]:
df["estado_civil"] = df["estado_civil"].map(mapa)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   renda_mensal        1000 non-null   int64
 1   score_credito       1000 non-null   int64
 2   estado_civil        1000 non-null   int64
 3   tempo_emprego_anos  1000 non-null   int64
 4   patrimonio          1000 non-null   int64
 5   dividas_pendentes   1000 non-null   int64
 6   risco               1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

In [39]:
df.head(10)

,renda_mensal,score_credito,estado_civil,tempo_emprego_anos,patrimonio,dividas_pendentes,risco
0,8470,505,0,0,73125,19317,1
1,2060,450,1,12,25078,7659,1
2,6590,480,0,17,47302,11655,0
3,14618,532,1,12,228795,31240,1
4,6391,684,2,17,95882,8680,0
5,13164,787,2,4,107506,27141,0
6,12484,537,1,12,224100,36984,1
7,6934,583,2,3,76409,34413,1
8,7465,800,0,16,70079,26044,0
9,1666,729,1,2,12136,2326,0

In [40]:
X = df.drop(columns=["risco"]).values
y = df["risco"].values

In [41]:
print("Shape X:", X.shape)
print("Shape y:", y.shape)

Shape X: (1000, 6)
Shape y: (1000,)

In [42]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

modelo = RandomForestClassifier()
modelo.fit(X_train,y_train)

predicions = modelo.predict(X_test)
accuracy = accuracy_score(y_test, predicions)
print(f"Acurácia: {accuracy:.2f}")

Acurácia: 0.81